### ISSUE TITLE
Deprecated/removed Laravel array helpers used in release

### ISSUE THREAD

**Issue by magnetas** [SocialiteProviders/Okta#3]
Current release counts on `array_get` helper which is removed in Laravel 6.

It's fixed in the master branch a couple of months ago (`Arr::get` is used instead) but new release is not created.

The helper is available as a separate package (`laravel/helpers`) but it's not required in this package, nor in `socialite/manager`

**Comment by dtgreenwood** [comment]
When will it be possible to get an updated composer package for this update so we can use it in Laravel 6?

**Comment by alexjustesen-mm** [comment]
Can we get a new tagged release for the updated Laravel helper?

**Comment by atymic** [comment]
Tagged, sorry for the delay everyone:

See parent issue:
https://github.com/SocialiteProviders/Providers/issues/368
